### ISSUE TITLE
Cannot export UV-unwrapped mesh

### ISSUE THREAD

**Issue by Jan-Ligudzinski** [KhronosGroup/glTF-Blender-Exporter#176]
**System**
Blender version: 2.79
OS: Arch Linux x86_64, fully updated as of 2018-03-17
**Problem**
Blender runs into the following problem when exporting a UV-unwrapped object to glTF:
```
Traceback (most recent call last):
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/__init__.py", line 488, in execute
    gltf = export_gltf(data, settings)
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 1992, in export_gltf
    ] for exporter in exporters
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 1992, in <dictcomp>
    ] for exporter in exporters
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 1991, in <listcomp>
    for data in state['input'].get(exporter.blender_key, [])
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 799, in export_mesh
    vert_list = {Vertex(mesh, loop): 0 for loop in mesh.loops}.keys()
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 799, in <dictcomp>
    vert_list = {Vertex(mesh, loop): 0 for loop in mesh.loops}.keys()
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 111, in __init__
    self.uvs = tuple(layer.data[loop_idx].uv[:] for layer in mesh.uv_layers)
  File "/home/jan/.config/blender/2.79/scripts/addons/blendergltf-master/blendergltf.py", line 111, in <genexpr>
    self.uvs = tuple(layer.data[loop_idx].uv[:] for layer in mesh.uv_layers)
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1

location: <unknown location>:-1
```
**Steps to reproduce**
Load the default Blender scene with a cube, a camera and a directional light. In Edit Mode, Unwrap the cube. Export to glTF with the default settings. The problem persists regardless of whether or not the unwrapped object has a material or texture assigned or of the UV mapping itself.
I have had this behavior happen in any scene with an unwrapped/textured object.

**Comment by Jan-Ligudzinski** [comment]
I confused this exporter with https://github.com/Kupoman/blendergltf.
