### ISSUE TITLE
Renaming file seems to break addon.

### ISSUE THREAD

**Issue by erikwoods** [KhronosGroup/glTF-Blender-Exporter#258]
I think I've noticed a small issue. If you change the filename of your .blend file after you've already used the addon, the addon can't seem to function anymore. Instead, I get this error:

```
Traceback (most recent call last):
  File "/Users/ewoods/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 282, in invoke
    setattr(self, k, v)
  File "/Users/ewoods/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/modules/bpy_types.py", line 611, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: expected a string enum, not int

location: <unknown location>:-1
```

For anyone else experiencing this issue: just append your stuff from the "broken" file to a new file and then run Make Local on all the things. Then you can save over the original file and it seems to work fine.

There may be other factors that contribute to the problem I saw. I will update if I can more consistently reproduce the error and learn something new.

**Comment by donmccurdy** [comment]
Which file has been renamed? The `.blend`, or some texture in the model?

**Comment by erikwoods** [comment]
The .blend. I'll edit for clarification.

**Comment by donmccurdy** [comment]
Resolved in new importer/exporter, glTF-Blender-IO.
