### ISSUE TITLE
bug:  ascii export fails when baking animation and using default material.

### ISSUE THREAD

**Issue by spiraloid** [KhronosGroup/glTF-Blender-Exporter#297]
Hello, I am trying to install the glTF2.0 exporter and have followed the instructions to the letter.

when I try to export a simple cube scene, I get the following error:

(I also note in the install that the version numer is 2.78, which is cool, but since so many things are broken still I can't use it.  Does this exporter work with 2.79?)

----

Traceback (most recent call last):
  File "/Users/bay/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 376, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/Users/bay/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2/gltf2_export.py", line 85, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "/Users/bay/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2824, in generate_glTF
    generate_images(operator, context, export_settings, glTF)
  File "/Users/bay/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2110, in generate_images
    create_image_file(context, blender_image, path, file_format)
  File "/Users/bay/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2/gltf2_create.py", line 351, in create_image_file
    copyfile(src_path, dst_path)
  File "/Applications/Blender/blender.app/Contents/Resources/2.79/python/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/Users/bay/Google Drive/Foo Foo/Foo/Items/Foo/../../../../../../../'

location: <unknown location>:-1

**Comment by spiraloid** [comment]
ok so I've found out a little more about what's going on.

if I bake the action before hand and use "pose" instead of object and disable export materials (I was using default blender material) the glTF file will export without error.

**Comment by spiraloid** [comment]
adding a blend file that will fail to export .gltf

( exporting the same file as .glb works fine)

the blender scene is it's a simple smoothed cube skinned to a single bone with a curve type set to bounce instead of bezier.

if the animation gets baked manually before export and export materials is false, it will export as .gltf without error.

[cube.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2376277/cube.blend.zip)

**Comment by donmccurdy** [comment]
This is now working correctly on the new exporter: https://github.com/KhronosGroup/glTF-Blender-IO.
