### ISSUE TITLE
Can't export from Blender 2.78c

### ISSUE THREAD

**Issue by mikeedwards** [KhronosGroup/glTF-Blender-Exporter#41]
When I try to export the provided test scenes (e.g. `03_all_animations.blend`), it fails and I get the following error:

```
Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/__init__.py", line 276, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_export.py", line 82, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2330, in generate_glTF
    generate_meshes(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 848, in generate_meshes
    internal_primitives = extract_primitives(glTF, blender_mesh, filtered_vertex_groups[name], export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_extract.py", line 361, in extract_primitives
    blender_mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs an UVMap, "(null)" not found, aborting


location: <unknown location>:-1

```

The addon was added by copying the `io_scene_gltf2` folder into the `/Applications/blender.app/Contents/Resources/2.78/scripts/addons/` directory.

**Comment by mikeedwards** [comment]
I get the same failure running the validation test from the command line, too:
```
/Applications/blender.app/Contents/MacOS/blender  --background --python vt_01_start_scene.py
```
```
Read new prefs: /Users/Mike_Edwards/Library/Application Support/Blender/2.78/config/userpref.blend
found bundled python: /Applications/blender.app/Contents/MacOS/../Resources/2.78/python
INFO: Starting glTF 2.0 export
INFO: Extracting primitive
Error: Tangent space computation needs an UVMap, "(null)" not found, aborting
Error: Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/__init__.py", line 276, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_export.py", line 82, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2330, in generate_glTF
    generate_meshes(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 848, in generate_meshes
    internal_primitives = extract_primitives(glTF, blender_mesh, filtered_vertex_groups[name], export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_extract.py", line 361, in extract_primitives
    blender_mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs an UVMap, "(null)" not found, aborting


location: /Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/bpy/ops.py:189

Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/__init__.py", line 276, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_export.py", line 82, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2330, in generate_glTF
    generate_meshes(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 848, in generate_meshes
    internal_primitives = extract_primitives(glTF, blender_mesh, filtered_vertex_groups[name], export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_extract.py", line 361, in extract_primitives
    blender_mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs an UVMap, "(null)" not found, aborting


location: /Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/bpy/ops.py:189

location: /Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/bpy/ops.py:189
Error: Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/__init__.py", line 276, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_export.py", line 82, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2330, in generate_glTF
    generate_meshes(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 848, in generate_meshes
    internal_primitives = extract_primitives(glTF, blender_mesh, filtered_vertex_groups[name], export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_extract.py", line 361, in extract_primitives
    bTraceback (most recent call last):
  File "/Users/Mike_Edwards/Documents/projects/glTF-Blender-Exporter-master/tests/vt_01_start_scene.py", line 29, in <module>
    bpy.ops.export_scene.gltf(filepath="temp/01_test.gltf", check_existing=True, export_normals=True, export_apply=False, export_materials=True, export_tangents=True, export_embed_images=False, export_texcoords=True, export_animations=True, export_bake_skins=False, export_displacement=False, export_cameras=True, export_extras=False, export_lights=False, export_common=False, export_selected=False, export_embed_buffers=False, export_colors=True, export_morph=True, export_indices='UNSIGNED_SHORT', export_current_frame=True, export_skins=True, export_strip=False, filter_glob="*.gltf")
  File "/Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/__init__.py", line 276, in execute
    return gltf2_export.save(self, context, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_export.py", line 82, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2330, in generate_glTF
    generate_meshes(operator, context, export_settings, glTF)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 848, in generate_meshes
    internal_primitives = extract_primitives(glTF, blender_mesh, filtered_vertex_groups[name], export_settings)
  File "/Applications/blender.app/Contents/Resources/2.78/scripts/addons/io_scene_gltf2/gltf2_extract.py", line 361, in extract_primitives
    blender_mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs an UVMap, "(null)" not found, aborting


location: /Applications/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/bpy/ops.py:189


... truncated
Blender quit
```

**Comment by UX3D-nopper** [comment]
Yes, I did break the code. This should fix it:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/6f464e05c6d8f5525e1d046df677df9d947dfbbf

**Comment by UX3D-nopper** [comment]
Added/enhanced the current tests:
https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/tests

'vt_02_all_scenes.py' is loading and exporting all available scenes with the standard export settings.
