### ISSUE TITLE
UnboundLocalError: local variable 'texcoord_index' referenced before assignment

### ISSUE THREAD

**Issue by ncoder** [KhronosGroup/glTF-Blender-Exporter#83]
Have you seen this before? any tips for unblocking?

I can PM you the model if you want. 

Traceback (most recent call last):
  File "C:\Users\ncoder\extern\glTF-Blender-Exporter\scripts\addons\io_scene_gltf2\__init__.py", line 328, in execute
    return gltf2_export.save(self, context, export_settings)
  File "C:\Users\ncoder\extern\glTF-Blender-Exporter\scripts\addons\io_scene_gltf2\gltf2_export.py", line 84, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "C:\Users\ncoder\extern\glTF-Blender-Exporter\scripts\addons\io_scene_gltf2\gltf2_generate.py", line 2838, in generate_glTF
    generate_meshes(operator, context, export_settings, glTF)
  File "C:\Users\ncoder\extern\glTF-Blender-Exporter\scripts\addons\io_scene_gltf2\gltf2_generate.py", line 1081, in generate_meshes
    internal_primitives = extract_primitives(glTF, blender_mesh, filtered_vertex_groups[name], export_settings)
  File "C:\Users\ncoder\extern\glTF-Blender-Exporter\scripts\addons\io_scene_gltf2\gltf2_extract.py", line 944, in extract_primitives
    pending_attributes['TEXCOORD_' + str(texcoord_index)] = textcoord
UnboundLocalError: local variable 'texcoord_index' referenced before assignment

location: <unknown location>:-1

**Comment by ncoder** [comment]
Gosh.
This looks like it's just a typo:

            textcoord_index = 0
            for textcoord in texcoords:
                pending_attributes['TEXCOORD_' + str(texcoord_index)] = textcoord
                textcoord_index += 1

texcoord_index vs textcoord_index

**Comment by UX3D-nopper** [comment]
Fixed it here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/810b522e7f26810f86d39778e445eba336b524a9
Strange, that it dod not occur earlier.

Thank you very much!
